### ISSUE TITLE
libstdc++-6.dll causes segfault in app compiled with Clang

### ISSUE THREAD

**Issue by procedural** [msys2/msys2.github.io#7]
I know it's a wrong place for posting errors from GNU C++ standard library, but currently crash happens only when application is compiled with Clang from MSYS2:

```cpp
#include <unordered_map>
#include <string>

int main()
{
  std::unordered_map<std::string, int> test;
  test["cool"] = 5;
}
```

```
Program received signal SIGSEGV, Segmentation fault.
0x000000006fc9a07b in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
(gdb) bt
#0  0x000000006fc9a07b in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
#1  0x00000000004019c6 in _M_insert_unique_node ()
    at C:\msys64\mingw64\bin/../include/c++/5.2.0\bits/hashtable.h:1594
#2  0x0000000000401962 in operator[] ()
    at C:\msys64\mingw64\bin/../include/c++/5.2.0\bits/hashtable_policy.h:625
#3  0x0000000000401622 in operator[] ()
    at C:\msys64\mingw64\bin/../include/c++/5.2.0\bits/unordered_map.h:672
#4  main () at ../src\main.cpp:7
```

Any ideas / suggestions how to debug it further? Is there any debug symbols available anywhere for libstdc++?

Thanks!

**Comment by procedural** [comment]
Sorry, just realized [MINGW-packages](https://github.com/Alexpux/MINGW-packages) is a better place to ask this!
